spring.application.name=taskManagementSystem


# -----------------------------
# Server Config
# -----------------------------
server.port=8080

# -----------------------------
# Database Config (MySQL)
# -----------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/todos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password= 9315#PrasanjeetBiswas

# -----------------------------
# JPA / Hibernate
# -----------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# -----------------------------
# Logging
# -----------------------------
logging.level.org.springframework=INFO
logging.level.com.tradeflow=DEBUG

#security user name 
spring.security.user.name=jeet
spring.security.user.password=1234